# Generated by Django 2.2 on 2019-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(db_index=True, max_length=30, verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Выбор спорта',
                'verbose_name_plural': 'Выбор спорта',
                'ordering': ['sport_name'],
            },
        ),
    ]
