# Generated by Django 2.2 on 2019-04-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctavka', '0002_auto_20190430_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=30, verbose_name='Итоги события')),
            ],
            options={
                'verbose_name': 'Итог',
                'verbose_name_plural': 'Итоги',
                'ordering': ['total'],
            },
        ),
        migrations.AlterField(
            model_name='ctavka',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ctavka.Sport', verbose_name='спорт'),
        ),
        migrations.AddField(
            model_name='ctavka',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ctavka.Total', verbose_name='итог ставки'),
        ),
    ]
