# Generated by Django 2.2 on 2019-04-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctavka', '0004_auto_20190430_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctavka',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ctavka.Sport', verbose_name='спорт'),
        ),
    ]
